# Generated by Django 4.2.15 on 2024-08-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheuler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_inicioSesion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoDocumento',
            field=models.CharField(choices=[('TI', 'TI'), ('CC', 'CC'), ('CE', 'CE')], max_length=100),
        ),
    ]
